# 1332. Remove Palindromic Subsequences
# Easy
# Topics
# premium lock icon
# Companies
# Hint
# You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

# Return the minimum number of steps to make the given string empty.

# A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

# A string is called palindrome if is one that reads the same backward as well as forward.

 

# Example 1:

# Input: s = "ababa"
# Output: 1
# Explanation: s is already a palindrome, so its entirety can be removed in a single step.
# Example 2:

# Input: s = "abb"
# Output: 2
# Explanation: "abb" -> "bb" -> "". 
# Remove palindromic subsequence "a" then "bb".
# Example 3:

# Input: s = "baabb"
# Output: 2
# Explanation: "baabb" -> "b" -> "". 
# Remove palindromic subsequence "baab" then "b".
 

# Constraints:

# 1 <= s.length <= 1000
# s[i] is either 'a' or 'b'.

class Solution:
    def removePalindromeSub(self, s: str) -> int:
        return 1 if s[:] == s[::-1] else 2
    
"""
Runtime is 0ms and in memory beating 48% + solutions.
That's the whole solution.
Question looks complicated to make you think twice but it has a reason to be an easy question.
Key observations:
either "a" or "b"

then you can form your subsequence by deleting any number of characters from string (being continous is 
not necessary)

so at minimal i can choose all a's from any index to form palindrome:
that will form : "aaaaa..." (count of a's)
similarly for b's. "bbbbbb..."
and then all are palindromes that we can delete in just two steps.
Unless string is itself a palindrome then we can delete it in just one step.
"""