# 389. Find the Difference
# Easy
# Topics
# premium lock icon
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        map = {}
        for i in s:
            if i in map:
                map[i] += 1
            else:
                map[i] = 1

        for i in t:
            if i not in map:
                return i

            else:
                map[i] -= 1
                if map[i] == 0:
                    del map[i]

"""
Following are most simple solutions:
from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        cs = Counter(s)
        ct = Counter(t)
        
        for ch in ct:
            if ct[ch] != cs[ch]:
                return ch

----------------------------------------------------------------------------------

XOR Method (Most Optimal & Interview Favorite)

XOR of same characters cancels out → only the extra character remains.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0
        for c in s + t:
            result ^= ord(c)
        return chr(result)



"""